apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: vote
  sessionAffinity: None
  type: ClusterIP